version: "3"
services:
  web:
    build: .
    ports:
      - "${PORT:-80}:80"
    volumes:
      - .:/app
    networks:
      - webnet

  db:
    image: mysql:latest
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
