"""empty message

Revision ID: 7a7ad496fa3d
Revises: 95187dbcb53b
Create Date: 2023-10-20 20:27:01.148039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a7ad496fa3d'
down_revision = '95187dbcb53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_description', sa.String(length=64), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('product_image', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('inventory_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inventory_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inventory_description', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inventory_stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inventory_price', mysql.FLOAT(), nullable=True),
    sa.Column('inventory_image', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('inventory_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('product')
    # ### end Alembic commands ###
